var files=new Array();
files.push(["KB","winsdk","A pure Win32 based MDI application.","KB/winsdk/Sigma.aspx@display=PrintAll.html"]);
files.push(["KB","atl","Beginner's Tutorial: COM/ATL Simple Project.","KB/atl/com_atl.aspx@display=PrintAll.html"]);
files.push(["KB","IP","An Asynchronous Pluggable Protocol Handler for data: URLs.","KB/IP/DataProtocol.aspx@display=PrintAll.html"]);
files.push(["KB","winhelp","A guide to MSDN Collection Integration.","KB/winhelp/msdnintegrator.aspx@display=PrintAll.html"]);
files.push(["KB","winsdk","Win32++: A Simple Alternative to MFC.","KB/winsdk/framework.aspx@display=PrintAll.html"]);
files.push(["KB","winsdk","JLib - A Windows Console Library.","KB/winsdk/JLib.aspx@display=PrintAll.html"]);
files.push(["KB","winsdk","A pure Win32 based MDI application.","KB/winsdk/Sigma.aspx@display=PrintAll.html"]);
files.push(["KB","winsdk","Adding Windows To Your Console Application.","KB/winsdk/winconsole.aspx@display=PrintAll.html"]);
